name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  my-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: My Build 
        run: mvn clean package

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
