name: Build WAR and Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'  # or your required version

    - name: Build WAR using Maven
      run: mvn clean package

    - name: List WAR file to confirm it's built
      run: ls -l target/*.war

    - name: Build Docker image with WAR file
      run: docker build -t my-image-name:$(date +%s) .
